# Generated by Django 6.0 on 2026-04-03 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
